#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using UnityEngine.Tilemaps;
using System.IO;

namespace LilFoots {
/// <summary>
/// UNITY-BUILT MAP SKIN (BudE, Sept 25 2026 ~11:45 PM ET: "we need to make sure we remove
/// ant art work and just have unity build it for the maps, its still turning out weird").
/// The hand-painted lf_*.png tiles and the painted sky are REMOVED from the map build.
/// Every terrain tile texture is now GENERATED BY UNITY at build time: seeded value-noise
/// moss caps with an organic dark fringe + light rim, strata'd forest dirt, shaded side
/// lips - no composited painting, no painted PNGs, nothing to go "weird". 256px @ 256ppu
/// = 1u = one tilemap cell (the seamless quad-mirror law stays).
/// </summary>
public static class LilFootsProcTiles {
    const int N = 256;   // 256px @ 256ppu = 1u per tile
    const string DIR = "Assets/Art/Tiles";

    static float Hash(int x, int y, int seed) {
        uint h = (uint)(x * 374761393 + y * 668265263 + seed * 2246822519);
        h = (h ^ (h >> 13)) * 1274126177;
        return ((h ^ (h >> 16)) & 0xffffff) / 16777215f;
    }
    static float VNoise(float x, float y, int seed) {
        int xi = Mathf.FloorToInt(x), yi = Mathf.FloorToInt(y);
        float xf = x - xi, yf = y - yi;
        float u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
        float a = Hash(xi, yi, seed), b = Hash(xi + 1, yi, seed);
        float c = Hash(xi, yi + 1, seed), d = Hash(xi + 1, yi + 1, seed);
        return Mathf.Lerp(Mathf.Lerp(a, b, u), Mathf.Lerp(c, d, u), v);
    }

    /// <summary>Moss grass cap: sage body, organic dark fringe along the top edge, light
    /// rim on the very top, per-pixel dither + sparse dark speckles. Fringe depth varies across X.</summary>
    static Texture2D CapTex(int variant, bool lipL, bool lipR) {
        int seed = 900 + variant * 17;
        var top  = new Color(0.63f, 0.72f, 0.55f);   // sage moss lit
        var mid  = new Color(0.44f, 0.57f, 0.38f);   // canon sage green
        var deep = new Color(0.30f, 0.41f, 0.27f);   // forest darks
        var tex = new Texture2D(N, N, TextureFormat.RGBA32, false);
        for (int y = 0; y < N; y++) {
            float fy = y / (float)N;
            var c = Color.Lerp(mid, deep, Mathf.Pow(fy, 1.2f));
            c = Color.Lerp(c, top, 0.55f * (1f - fy));
            for (int x = 0; x < N; x++) {
                float d1 = Hash(x, y, seed);
                float dn = VNoise(x * 0.23f, y * 0.23f, seed + 3);
                var px = c * (0.90f + 0.14f * dn + 0.06f * d1);
                // organic moss fringe at the tile's TOP edge: depth varies across X (wraps)
                float wave = Mathf.Sin(x * 2f * Mathf.PI / N * 3f + variant) * 3.5f
                           + Mathf.Sin(x * 2f * Mathf.PI / N * 7f + variant * 2f) * 2.5f;
                int fringe = Mathf.RoundToInt(16 + wave);
                int fromTop = N - 1 - y;
                if (fromTop < fringe) {
                    float t = 1f - fromTop / (float)fringe;
                    px = Color.Lerp(px, deep * 0.72f, 0.85f * t);
                }
                if (fromTop < 3) px = Color.Lerp(px, top * 1.18f, 0.55f);
                if (Hash(x, y, seed + 7) > 0.986f) px *= 0.66f;
                if (lipL && x < 16)  px *= (x < 3) ? 1.14f : 0.74f;
                if (lipR && x > N - 17) px *= (x > N - 4) ? 1.14f : 0.74f;
                tex.SetPixel(x, y, px);
            }
        }
        tex.Apply();
        return tex;
    }

    /// <summary>Forest dirt fill: deep earth browns, wavy darker strata, dither + root speckles.</summary>
    static Texture2D DirtTex(int variant, bool lipL, bool lipR) {
        int seed = 1700 + variant * 23;
        var top  = new Color(0.34f, 0.30f, 0.21f);
        var deep = new Color(0.17f, 0.16f, 0.11f);
        var tex = new Texture2D(N, N, TextureFormat.RGBA32, false);
        for (int y = 0; y < N; y++) {
            float fy = y / (float)N;
            var c = Color.Lerp(deep, top, 0.35f * (1f - fy));
            for (int x = 0; x < N; x++) {
                float dn = VNoise(x * 0.19f, y * 0.19f, seed + 5);
                var px = c * (0.88f + 0.20f * dn);
                float band = Mathf.Sin((y + Mathf.Sin(x * 2f * Mathf.PI / N) * 6f) * 0.35f + variant);
                if (band > 0.93f) px *= 0.80f;
                if (Hash(x, y, seed + 9) > 0.991f) px *= 0.62f;
                if (lipL && x < 16)  px *= (x < 3) ? 1.10f : 0.72f;
                if (lipR && x > N - 17) px *= (x > N - 4) ? 1.10f : 0.72f;
                tex.SetPixel(x, y, px);
            }
        }
        tex.Apply();
        return tex;
    }

    /// <summary>Unity-generated sky: pale-sage overcast gradient + two forest-ridge
    /// silhouettes fading into mist. 512x256, camera-pinned backdrop for tilemap maps.</summary>
    public static Texture2D SkyTex() {
        const int W = 512, H = 256;
        var tex = new Texture2D(W, H, TextureFormat.RGBA32, false);
        for (int y = 0; y < H; y++) {
            float fy = y / (float)H;
            var sky = Color.Lerp(new Color(0.72f, 0.78f, 0.74f), new Color(0.86f, 0.90f, 0.87f), Mathf.Pow(fy, 1.35f));
            sky = Color.Lerp(sky, new Color(0.90f, 0.93f, 0.91f), 0.5f * Mathf.Clamp01((fy - 0.62f) / 0.38f));
            for (int x = 0; x < W; x++) {
                var px = sky;
                px *= 0.97f + 0.03f * VNoise(x * 0.11f, y * 0.11f, 77);
                float r1 = 0.55f + 0.10f * Mathf.Sin(x * 2f * Mathf.PI / W * 3f) + 0.05f * VNoise(x * 0.05f, 0f, 91);
                float r2 = 0.42f + 0.08f * Mathf.Sin(x * 2f * Mathf.PI / W * 5f + 1.3f) + 0.05f * VNoise(x * 0.07f, 9f, 93);
                if (fy < r1) px = Color.Lerp(px, new Color(0.42f, 0.53f, 0.44f), 0.85f);
                if (fy < r2) px = Color.Lerp(px, new Color(0.20f, 0.29f, 0.22f), 0.95f);
                tex.SetPixel(x, y, px);
            }
        }
        tex.Apply();
        return tex;
    }

    static int VariantOf(string name) {
        char c = name.Length > 0 ? name[name.Length - 1] : 'a';
        return char.IsDigit(c) ? (c - '0') : (char.ToLower(c) - 'a');
    }

    /// <summary>Generates the PNG if missing (Unity builds it), imports at 256ppu, and
    /// returns a persistent Tile asset. No painted art is loaded - the file at
    /// Assets/Art/Tiles/<name>.png IS the Unity-generated skin.</summary>
    public static TileBase EnsureTile(string name) {
        Directory.CreateDirectory(DIR);
        string png = DIR + "/" + name + ".png";
        string asset = DIR + "/" + name + ".asset";
        if (!File.Exists(png)) {
            bool dirt = name.Contains("dirt");
            bool lipL = name.EndsWith("_l");
            bool lipR = name.EndsWith("_r");
            Texture2D tex = dirt ? DirtTex(VariantOf(name), lipL, lipR)
                                 : CapTex(VariantOf(name), lipL, lipR);
            File.WriteAllBytes(png, tex.EncodeToPNG());
        }
        var ti = (TextureImporter)AssetImporter.GetAtPath(png);
        ti.textureType = TextureImporterType.Sprite;
        ti.spriteImportMode = SpriteImportMode.Single;
        ti.spritePixelsPerUnit = 256f;
        ti.filterMode = FilterMode.Bilinear;
        ti.mipmapEnabled = false;
        ti.SaveAndReimport();
        var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(png);
        var t = AssetDatabase.LoadAssetAtPath<UnityEngine.Tilemaps.Tile>(asset);
        if (t == null) {
            t = ScriptableObject.CreateInstance<UnityEngine.Tilemaps.Tile>();
            AssetDatabase.CreateAsset(t, asset);
        }
        // REBIND LAW (Sept 25): the tile binds whatever the PNG says TODAY.
        t.sprite = sprite;
        t.name = name;
        EditorUtility.SetDirty(t);
        return t;
    }

    /// <summary>The Unity-generated sky as a loadable Sprite (camera-pinned backdrop).</summary>
    public static Sprite EnsureSky() {
        const string path = "Assets/Art/Generated/unity_sky.png";
        Directory.CreateDirectory("Assets/Art/Generated");
        if (!File.Exists(path)) File.WriteAllBytes(path, SkyTex().EncodeToPNG());
        var ti = (TextureImporter)AssetImporter.GetAtPath(path);
        ti.textureType = TextureImporterType.Sprite;
        ti.spriteImportMode = SpriteImportMode.Single;
        ti.spritePixelsPerUnit = 100f;
        ti.SaveAndReimport();
        return AssetDatabase.LoadAssetAtPath<Sprite>(path);
    }
}
}
#endif
