#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using UnityEngine.Tilemaps;
using System.Collections.Generic;
using System.IO;

namespace LilFoots {
/// <summary>
/// UNITY TILEMAP SKIN (BudE, Sept 25 2026: "remove ant art work and just have unity build
/// it for the maps"). The terrain where the player runs is a REAL Unity Tilemap, and the
/// tile TEXTURES ARE GENERATED BY UNITY (LilFootsProcTiles - seeded noise moss caps, strata
/// dirt, shaded lips). No painted art files are loaded for the map skin. Each audited
/// ground collider gets its footprint painted as 1u tiles - a grass-cap row plus
/// dirt-fill rows down to bedrock, with lip tiles on exposed side columns.
///
/// LAW: the tilemap is the SKIN ONLY. Physics stays on the audited BoxCollider2D Plat
/// objects - zero gameplay drift, the geometry he judged GREEN is exactly what ships.
/// Tile cells sit at the 1u Unity grid, tilemap offset y=+0.2 so the tile top edge lands
/// exactly on the 6.2u ground surface; the 0.2u plateau difference is absorbed by the
/// grass-edge fringe band (ArtPass binds it above every walking line).
/// 1 tile = 1 Unity unit: the layout stays editable/reskinnable with the Unity Tile
/// Palette - drop hand-painted art over the same lf_*.png files and the world reskins.
/// </summary>
public static class LilFootsTilemapSkin {
    static Tilemap _tm;
    static TileBase[] _caps, _capsL, _capsR, _dirts, _dirtsL, _dirtsR;
    static bool _ready;

    public static bool Ready() { return _ready || LoadTiles(); }

    static Tilemap EnsureTilemap(Transform root) {
        if (_tm != null) return _tm;
        var gridGo = new GameObject("TerrainGrid");
        gridGo.transform.SetParent(root, false);
        gridGo.AddComponent<Grid>();
        var tmGo = new GameObject("TerrainTiles");
        tmGo.transform.SetParent(gridGo.transform, false);
        var tm = tmGo.AddComponent<Tilemap>();
        var tr = tmGo.AddComponent<TilemapRenderer>();
        tr.sortingOrder = -2;                          // same plane the old earth bands drew on
        tr.mode = TilemapRenderer.Mode.Chunk;
        tmGo.transform.localPosition = new Vector3(0f, 0.2f, 0f);  // tile top edge = 6.2 surface
        _tm = tm;
        return tm;
    }

    /// <summary>[UNITY-BUILT SKIN Sept 25] Tiles come from LilFootsProcTiles - Unity
    /// generates the textures at build time; no painted lf_*.png art is ever loaded.</summary>
    static bool LoadTiles() {
        _caps   = LoadSet("lf_grass_a", "lf_grass_b", "lf_grass_c", "lf_grass_d");
        _capsL  = LoadSet("lf_grass_l");
        _capsR  = LoadSet("lf_grass_r");
        _dirts  = LoadSet("lf_dirt_a", "lf_dirt_b", "lf_dirt_c", "lf_dirt_d");
        _dirtsL = LoadSet("lf_dirt_l");
        _dirtsR = LoadSet("lf_dirt_r");
        // painted template (verdict-locked) overrides the procedural set when present
        if (PaintedTerrainReady()) {
            var pc = SlicePainted("Assets/Art/art_terrain_paint.png", 0);
            var pd = SlicePainted("Assets/Art/art_terrain_paint.png", 1);
            if (pc.Length > 0 && pd.Length > 0) {
                _caps = pc; _dirts = pd;
                _capsL = new TileBase[] { pc[0] }; _capsR = new TileBase[] { pc[pc.Length - 1] };
                _dirtsL = new TileBase[] { pd[0] }; _dirtsR = new TileBase[] { pd[pd.Length - 1] };
                Debug.Log("[TilemapSkin] PAINTED terrain template active (BudE verdict-locked)");
            }
        }
        _ready = _caps.Length > 0 && _dirts.Length > 0;
        if (_ready) Debug.Log("[TilemapSkin] UNITY-GENERATED tiles ready: " + _caps.Length + " caps + "
                              + _dirts.Length + " dirt (+lip variants: " + (_capsL.Length + _capsR.Length + _dirtsL.Length + _dirtsR.Length) + ")");
        else Debug.LogWarning("[TilemapSkin] procedural tile generation failed");
        return _ready;
    }

    static TileBase[] LoadSet(params string[] names) {
        var list = new List<TileBase>();
        foreach (var n in names) { var t = LilFootsProcTiles.EnsureTile(n); if (t != null) list.Add(t); }
        return list.ToArray();
    }

    // [PAINTED TEMPLATE PRIORITY Sept 27 PM - BudE: "I want us to generate templates and
    // that's how the maps should actually look"] when a painted terrain template exists
    // (art_terrain_paint.png, generated in the characters' own style and verdict-locked
    // by BudE), it REPLACES the procedural tile set: sliced into cap tiles (top band,
    // the mossy grass line) and dirt tiles (fill below), left/right lip variants mirrored
    // from the edge columns. No file = zero behavior change (procedural fallback).
    static TileBase[] SlicePainted(string path, int band) {
        var bytes = System.IO.File.ReadAllBytes(path);
        var tex = new UnityEngine.Texture2D(2, 2);
        if (!tex.LoadImage(bytes)) return new TileBase[0];
        int N = 128;
        int cols = Mathf.Max(1, tex.width / N);
        var set = new List<TileBase>();
        for (int cx = 0; cx < cols; cx++) {
            var t = new UnityEngine.Texture2D(N, N);
            int sy = band == 0 ? 0 : N;   // band 0 = top (grass cap), band 1 = fill (earth)
            t.SetPixels(tex.GetPixels(cx * N, Mathf.Max(0, tex.height - sy - N), N, N));
            t.Apply();
            Sprite s = UnityEngine.Sprite.Create(t, new UnityEngine.Rect(0, 0, N, N), new UnityEngine.Vector2(0.5f, 0.5f), 100f);
            var tile = UnityEngine.ScriptableObject.CreateInstance<UnityEngine.Tilemaps.Tile>();
            tile.sprite = s; tile.flags = UnityEngine.Tilemaps.TileFlags.None;
            set.Add(tile);
        }
        Debug.Log("[TilemapSkin] painted template sliced: " + set.Count + " tiles (band " + band + ")");
        return set.ToArray();
    }

    static bool PaintedTerrainReady() {
        return System.IO.File.Exists("Assets/Art/art_terrain_paint.png");
    }

    static int Hash(int c, int r) { return ((c * 73856093) ^ (r * 19349663)) & 0x7fffffff; }

    /// <summary>Pre-pass: the union of every ground's tile cells, so lips only paint on
    /// TRULY exposed sides (adjacent grounds don't get seam lips where they meet).</summary>
    static HashSet<long> CollectCells(System.Collections.Generic.IEnumerable<GameObject> grounds) {
        var cells = new HashSet<long>();
        foreach (var plat in grounds) {
            var bc = plat.GetComponent<BoxCollider2D>();
            if (bc == null || bc.size.y < 2f) continue;             // hops wear slab art, not tiles
            float top = plat.transform.position.y + bc.size.y / 2f;
            float x0 = plat.transform.position.x - bc.size.x / 2f;
            float x1 = plat.transform.position.x + bc.size.x / 2f;
            int c0 = Mathf.FloorToInt(x0 + 0.001f);
            int c1 = Mathf.CeilToInt(x1 - 0.001f) - 1;
            int rTop = Mathf.RoundToInt(top - 1.2f);                 // tile top edge at the surface
            for (int c = c0; c <= c1; c++)
                for (int r = rTop; r >= -6; r--)                     // bedrock: solid to below frame
                    cells.Add(((long)c << 32) ^ (uint)r);
        }
        return cells;
    }

    /// <summary>Paint every audited ground collider's footprint as tiles (skin only).</summary>
    static bool _painted;

    public static void PaintGrounds(GameObject mapRoot) {
        if (!Ready() || _painted) return;   // one union paint per session (loop calls per-plat)
        _painted = true;
        var grounds = new List<GameObject>();
        foreach (Transform child in mapRoot.transform) {
            var bc = child.GetComponent<BoxCollider2D>();
            if (bc != null && bc.size.y >= 2f) grounds.Add(child.gameObject);
        }
        var cells = CollectCells(grounds);
        bool Has(int c, int r) => cells.Contains(((long)c << 32) ^ (uint)r);

        var tm = EnsureTilemap(mapRoot.transform);
        int painted = 0, caps = 0, lips = 0;
        foreach (var key in cells) {
            int c = (int)(key >> 32); int r = (int)(key & 0xffffffffL);
            bool top = !Has(c, r + 1);
            bool openL = !Has(c - 1, r);
            bool openR = !Has(c + 1, r);
            TileBase t;
            if (top) {
                if (openL && _capsL.Length > 0) { t = _capsL[0]; lips++; }
                else if (openR && _capsR.Length > 0) { t = _capsR[0]; lips++; }
                else { t = _caps[Hash(c, r) % _caps.Length]; caps++; }
            } else {
                if (openL && _dirtsL.Length > 0) t = _dirtsL[0];
                else if (openR && _dirtsR.Length > 0) t = _dirtsR[0];
                else if (_dirts.Length > 0) {
                    // [STORYBOOK Sept 27 PM] DEPTH-ORDERED soil: the deeper the cell sits
                    // below the grass cap, the darker its tile variant - the ground reads
                    // like a storybook earth cross-section instead of a random speckle.
                    int k = 0; while (Has(c, r + k + 1)) k++;
                    t = _dirts[Mathf.Min(_dirts.Length - 1, k / 2)];
                }
            }
            tm.SetTile(new Vector3Int(c, r, 0), t);
            painted++;
        }
        tm.CompressBounds();
        Debug.Log("[TilemapSkin] painted " + painted + " tiles (" + caps + " grass caps, " + lips + " exposed lips) across " + grounds.Count + " grounds");
    }
}
}
#endif
